### ISSUE TITLE
/media/examples/beach.jpg is missing

### ISSUE THREAD

**Issue by habi** [worldveil/photomosaic#2]
Thanks for providing the code.
But I cannot run the example mentioned in the README, since the `beach.jpg` example image is missing.

**Comment by worldveil** [comment]
Ah yes. Well it's a family photo of mine complete with EXIF tags, lat/lon etc so I didn't add it to the repo. I'll probably add some example though since I like it when users can just pull & run examples.

**Comment by habi** [comment]
Understandable!

Is there a way of chatting with you? I've run into a bunch of other things which I'd first like to discuss instead of opening an issue here.
Maybe gitter.im, or directly via email?
