### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by rafaelpini** [worldveil/photomosaic#9]
I'm trying to install on Centos 7 (new install) and the build fails: 

 File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-S23qGD/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ANToly/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-S23qGD/dlib/
The command '/bin/sh -c pip install -r /home/requirements.txt' returned a non-zero code: 1

It looks like it is related to dlib, known for being difficult to get up and running. Is this library only required for the facil recognition stuff? I would disable it that's the only use.

**Comment by rafaelpini** [comment]
I also tried to build on a brand new ubuntu install and also got errors:

[ 72%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
    In file included from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics/../optimization/../geometry.h:10:0,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics/../optimization/max_sum_submatrix.h:10,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics/../optimization.h:15,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics/vector_normalizer_frobmetric.h:8,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics.h:13,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/assign_image.h:8,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/python/numpy_image.h:14,
                     from /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/python.h:9,
                     from /tmp/pip-install-2qDJdG/dlib/tools/python/src/opaque_types.h:6,
                     from /tmp/pip-install-2qDJdG/dlib/tools/python/src/vector.cpp:4:
    /tmp/pip-install-2qDJdG/dlib/dlib/../dlib/image_transforms/../statistics/../optimization/../geometry/point_transforms.h:732:9: internal compiler error: Segmentation fault
             }
             ^
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    CMakeFiles/dlib_python.dir/build.make:110: recipe for target 'CMakeFiles/dlib_python.dir/src/vector.cpp.o' failed
    make[2]: *** [CMakeFiles/dlib_python.dir/src/vector.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
    make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2qDJdG/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/opt/conda/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/conda/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/opt/conda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/opt/conda/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/opt/conda/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-2qDJdG/dlib/setup.py", line 135, in run
        self.build_extension(ext)
      File "/tmp/pip-install-2qDJdG/dlib/setup.py", line 175, in build_extension
        subprocess.check_call(cmake_build, cwd=build_folder)
      File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-2qDJdG/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-CeideA/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-2qDJdG/dlib/
The command '/bin/sh -c pip install -r /home/requirements.txt' returned a non-zero code: 1

**Comment by worldveil** [comment]
yes, dlib is used for the facial landmark calculation. why won't the docker solution work for you? I deliberately used docker for this reason - some of these deps are annoying to set up.

**Comment by rafaelpini** [comment]
I´m new to docker and Dlib, so I don´t really know why that happened. I´ve commented all references to Dlib and then it worked (without starting any of the face recognition features, of course).

I think that dlib might need some other hardware or other hardware specific drivers.

Your script is awesome and I didn´t need the facial features anyway, keep up the good work!
